// pratar-me-site/src/App.vue
<script setup lang="ts">
import TitleBox from "./components/TitleBox/TitleBox.vue";
import ConvoPanel from "./components/ConvoPanel/ConvoPanel.vue";
import MainBox from "./components/MainBox/MainBox.vue";
</script>

<template>
  <main>
    <section class="leftContainer">
      <ConvoPanel class="ConvoPanel" />
    </section>
    <section class="rightContainer">
      <TitleBox />
      <MainBox />
    </section>
  </main>
</template>

<style scoped>
.leftContainer {
  width: calc(20% - 30px );
  margin-left: 20px;
}

.rightContainer {
  display: flexbox;
  float: right;
  margin-right: 20px;
  width: calc(80% - 30px);
  flex-direction: column;
}
</style>

// pratar-me-site/src/App.svelte
<script lang="ts">
  import NameBar from "./components/NameBar/NameBar.svelte";
  import MainBox from "./components/MainBox/MainBox.svelte";
  import ConvoPanel from "./components/ConvoPanel/ConvoPanel.svelte";
  import { conversations, selfUser } from "./stores";
  import type { Conversation, Message, User } from "./types";
  

  let self = $selfUser;
  let convos = $conversations;
  let currentConvo = $conversations[0];
</script>

<main>
  <div class="leftContainer">
    <ConvoPanel />
  </div>
  <div class="rightContainer">
    <NameBar user={self} />
    <MainBox />
  </div>
</main>

<style>
  main {
    margin: 20px;
    height: calc(100vh - 40px);
  }

  .leftContainer {
    display: flex;
    flex-direction: column;
    float: left;
    width: 20%;
    height: inherit;
  }

  .rightContainer {
    margin-left: 10px;
    float: right;
    width: calc(80% - 20px);
    height: inherit;
    display: flex;
    flex-direction: column;
  }
</style>
